/** @type {import('@commitlint/types').UserConfig} */
export default {
  extends: ['@commitlint/config-conventional'],
  prompt: {
    aiNumber: 1,
    allowBreakingChanges: ['feat', 'fix'],
    allowCustomIssuePrefix: true,
    allowCustomScopes: true,
    allowEmptyIssuePrefix: true,
    allowEmptyScopes: true,
    breaklineChar: '|',
    breaklineNumber: 100,
    confirmColorize: true,
    customIssuePrefixAlias: 'custom',
    customIssuePrefixAlign: 'top',
    customScopesAlias: 'custom',
    customScopesAlign: 'bottom',
    defaultBody: '',
    defaultIssues: '',
    defaultScope: '',
    defaultSubject: '',
    emojiAlign: 'center',
    emptyIssuePrefixAlias: 'skip',
    emptyScopesAlias: 'empty',
    issuePrefixes: [{ name: 'closed:   ISSUES has been processed', value: 'closed' }],
    markBreakingChangeMode: false,
    maxHeaderLength: Number.POSITIVE_INFINITY,
    maxSubjectLength: Number.POSITIVE_INFINITY,
    messages: {
      body: '填写更加详细的变更描述（可选）。使用 "|" 换行 :\n',
      breaking: '列举非兼容性重大的变更（可选）。使用 "|" 换行 :\n',
      confirmCommit: '是否提交或修改commit ?',
      customScope: '请输入自定义的提交范围 :',
      footer: '列举关联issue (可选) 例如: #31, #I3244 :\n',
      footerPrefixesSelect: '选择关联issue前缀（可选）:',
      generatedSelectByAI: '选择一个 AI 生成的简短描述:',
      generatingByAI: '正在通过 AI 生成你的提交简短描述...',
      scope: '选择一个提交范围（可选）:',
      subject: '填写简短精炼的变更描述 :\n',
      type: "选择你要提交的类型",
    },
    minSubjectLength: 0,
    scopeOverrides: undefined,
    scopes: [],
    skipQuestions: [],
    themeColorCode: '',
    types: [
      { emoji: ":sparkles:", name: "特性: ✨新增功能", value: "feat" },
      { emoji: ":bug:", name: "修复: 🐛修复缺陷", value: "fix" },
      { emoji: ":memo:", name: "文档: 📝文档变更", value: "docs" },
      { emoji: ":lipstick:", name: "格式: 💄代码格式（不影响功能，例如空格、分号等格式修正）", value: "style" },
      { emoji: ":recycle:", name: "重构: ♻️代码重构（不包括 bug 修复、功能新增）", value: "refactor" },
      { emoji: ":zap:", name: "性能: ⚡️性能优化", value: "perf" },
      { emoji: ":white_check_mark:", name: "测试: ✅添加疏漏测试或已有测试改动", value: "test" },
      { emoji: ":package:", name: "构建: 📦️构建流程、外部依赖变更（如升级 npm 包、修改 vite 配置等）", value: "build" },
      { emoji: ":ferris_wheel:", name: "集成: 🎡修改 CI 配置、脚本", value: "ci" },
      { emoji: ":rewind:", name: "回退: ⏪️回滚 commit", value: "revert" },
      { emoji: ":hammer:", name: "其他: 🔨对构建过程或辅助工具和库的更改（不影响源文件、测试用例）", value: "chore" },
    ],
    upperCaseSubject: false,
    useAI: false,
    useEmoji: true,
  },
  // see https://commitlint.js.org/#/reference-rules
  rules: {}
}